/**
 * Error Constants
 * 
 * Constants for error codes, categories, and standardized error messages.
 * 
 * @author Gil Klainert
 * @version 1.0.0
 */

import type { ErrorCategory, ErrorSeverity } from '../types';

// ============================================================================
// ERROR CATEGORIES
// ============================================================================

export const ERROR_CATEGORIES = {
  VALIDATION: 'validation',
  AUTHENTICATION: 'authentication',
  AUTHORIZATION: 'authorization',
  NETWORK: 'network',
  DATABASE: 'database',
  PROCESSING: 'processing',
  EXTERNAL_SERVICE: 'external_service',
  SYSTEM: 'system',
  USER_INPUT: 'user_input',
  BUSINESS_LOGIC: 'business_logic'
} as const satisfies Record<string, ErrorCategory>;

// ============================================================================
// ERROR SEVERITY LEVELS
// ============================================================================

export const ERROR_SEVERITY_LEVELS = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  CRITICAL: 'critical'
} as const satisfies Record<string, ErrorSeverity>;

// ============================================================================
// COMMON ERROR CODES
// ============================================================================

export const ERROR_CODES = {
  // Validation Errors (1000-1999)
  VALIDATION_FAILED: 'ERR_1000',
  REQUIRED_FIELD_MISSING: 'ERR_1001',
  INVALID_FORMAT: 'ERR_1002',
  VALUE_OUT_OF_RANGE: 'ERR_1003',
  INVALID_EMAIL: 'ERR_1004',
  INVALID_PHONE: 'ERR_1005',
  INVALID_URL: 'ERR_1006',
  INVALID_DATE: 'ERR_1007',
  INVALID_PASSWORD: 'ERR_1008',
  PASSWORD_TOO_WEAK: 'ERR_1009',
  INVALID_FILE_TYPE: 'ERR_1010',
  FILE_TOO_LARGE: 'ERR_1011',
  
  // Authentication Errors (2000-2999)
  INVALID_CREDENTIALS: 'ERR_2000',
  TOKEN_EXPIRED: 'ERR_2001',
  TOKEN_INVALID: 'ERR_2002',
  TOKEN_MISSING: 'ERR_2003',
  LOGIN_FAILED: 'ERR_2004',
  REGISTRATION_FAILED: 'ERR_2005',
  EMAIL_NOT_VERIFIED: 'ERR_2006',
  ACCOUNT_LOCKED: 'ERR_2007',
  TOO_MANY_LOGIN_ATTEMPTS: 'ERR_2008',
  
  // Authorization Errors (3000-3999)
  UNAUTHORIZED: 'ERR_3000',
  FORBIDDEN: 'ERR_3001',
  INSUFFICIENT_PERMISSIONS: 'ERR_3002',
  RESOURCE_ACCESS_DENIED: 'ERR_3003',
  FEATURE_NOT_AVAILABLE: 'ERR_3004',
  SUBSCRIPTION_REQUIRED: 'ERR_3005',
  
  // Network Errors (4000-4999)
  NETWORK_ERROR: 'ERR_4000',
  REQUEST_TIMEOUT: 'ERR_4001',
  CONNECTION_REFUSED: 'ERR_4002',
  DNS_ERROR: 'ERR_4003',
  SSL_ERROR: 'ERR_4004',
  PROXY_ERROR: 'ERR_4005',
  
  // Database Errors (5000-5999)
  DATABASE_ERROR: 'ERR_5000',
  CONNECTION_FAILED: 'ERR_5001',
  QUERY_FAILED: 'ERR_5002',
  TRANSACTION_FAILED: 'ERR_5003',
  CONSTRAINT_VIOLATION: 'ERR_5004',
  DUPLICATE_ENTRY: 'ERR_5005',
  RECORD_NOT_FOUND: 'ERR_5006',
  OPTIMISTIC_LOCK_EXCEPTION: 'ERR_5007',
  
  // Processing Errors (6000-6999)
  PROCESSING_FAILED: 'ERR_6000',
  PARSING_FAILED: 'ERR_6001',
  GENERATION_FAILED: 'ERR_6002',
  ANALYSIS_FAILED: 'ERR_6003',
  OPTIMIZATION_FAILED: 'ERR_6004',
  CONVERSION_FAILED: 'ERR_6005',
  PROCESSING_TIMEOUT: 'ERR_6006',
  PROCESSING_CANCELLED: 'ERR_6007',
  INSUFFICIENT_RESOURCES: 'ERR_6008',
  QUEUE_FULL: 'ERR_6009',
  
  // External Service Errors (7000-7999)
  EXTERNAL_SERVICE_ERROR: 'ERR_7000',
  API_RATE_LIMIT: 'ERR_7001',
  API_QUOTA_EXCEEDED: 'ERR_7002',
  SERVICE_UNAVAILABLE: 'ERR_7003',
  SERVICE_TIMEOUT: 'ERR_7004',
  INVALID_API_RESPONSE: 'ERR_7005',
  AI_SERVICE_ERROR: 'ERR_7006',
  STORAGE_SERVICE_ERROR: 'ERR_7007',
  EMAIL_SERVICE_ERROR: 'ERR_7008',
  
  // System Errors (8000-8999)
  INTERNAL_ERROR: 'ERR_8000',
  CONFIG_ERROR: 'ERR_8001',
  SYSTEM_OVERLOAD: 'ERR_8002',
  MAINTENANCE_MODE: 'ERR_8003',
  FEATURE_DISABLED: 'ERR_8004',
  VERSION_MISMATCH: 'ERR_8005',
  DEPENDENCY_ERROR: 'ERR_8006',
  
  // User Input Errors (9000-9999)
  INVALID_INPUT: 'ERR_9000',
  MALFORMED_REQUEST: 'ERR_9001',
  MISSING_PARAMETERS: 'ERR_9002',
  INVALID_PARAMETERS: 'ERR_9003',
  UNSUPPORTED_OPERATION: 'ERR_9004',
  
  // Business Logic Errors (10000-10999)
  BUSINESS_RULE_VIOLATION: 'ERR_10000',
  WORKFLOW_ERROR: 'ERR_10001',
  STATE_TRANSITION_ERROR: 'ERR_10002',
  PRECONDITION_FAILED: 'ERR_10003',
  POSTCONDITION_FAILED: 'ERR_10004',
  INVARIANT_VIOLATION: 'ERR_10005'
} as const;

// ============================================================================
// ERROR MESSAGES
// ============================================================================

export const ERROR_MESSAGES = {
  [ERROR_CODES.VALIDATION_FAILED]: 'Validation failed',
  [ERROR_CODES.REQUIRED_FIELD_MISSING]: 'Required field is missing',
  [ERROR_CODES.INVALID_FORMAT]: 'Invalid format',
  [ERROR_CODES.VALUE_OUT_OF_RANGE]: 'Value is out of allowed range',
  [ERROR_CODES.INVALID_EMAIL]: 'Invalid email address',
  [ERROR_CODES.INVALID_PHONE]: 'Invalid phone number',
  [ERROR_CODES.INVALID_URL]: 'Invalid URL',
  [ERROR_CODES.INVALID_DATE]: 'Invalid date',
  [ERROR_CODES.INVALID_PASSWORD]: 'Invalid password format',
  [ERROR_CODES.PASSWORD_TOO_WEAK]: 'Password is too weak',
  [ERROR_CODES.INVALID_FILE_TYPE]: 'Unsupported file type',
  [ERROR_CODES.FILE_TOO_LARGE]: 'File size exceeds limit',
  
  [ERROR_CODES.INVALID_CREDENTIALS]: 'Invalid credentials',
  [ERROR_CODES.TOKEN_EXPIRED]: 'Access token has expired',
  [ERROR_CODES.TOKEN_INVALID]: 'Invalid access token',
  [ERROR_CODES.TOKEN_MISSING]: 'Access token is missing',
  [ERROR_CODES.LOGIN_FAILED]: 'Login failed',
  [ERROR_CODES.REGISTRATION_FAILED]: 'Registration failed',
  [ERROR_CODES.EMAIL_NOT_VERIFIED]: 'Email address not verified',
  [ERROR_CODES.ACCOUNT_LOCKED]: 'Account is locked',
  [ERROR_CODES.TOO_MANY_LOGIN_ATTEMPTS]: 'Too many login attempts',
  
  [ERROR_CODES.UNAUTHORIZED]: 'Unauthorized access',
  [ERROR_CODES.FORBIDDEN]: 'Access forbidden',
  [ERROR_CODES.INSUFFICIENT_PERMISSIONS]: 'Insufficient permissions',
  [ERROR_CODES.RESOURCE_ACCESS_DENIED]: 'Resource access denied',
  [ERROR_CODES.FEATURE_NOT_AVAILABLE]: 'Feature not available',
  [ERROR_CODES.SUBSCRIPTION_REQUIRED]: 'Premium subscription required',
  
  [ERROR_CODES.NETWORK_ERROR]: 'Network error occurred',
  [ERROR_CODES.REQUEST_TIMEOUT]: 'Request timeout',
  [ERROR_CODES.CONNECTION_REFUSED]: 'Connection refused',
  [ERROR_CODES.DNS_ERROR]: 'DNS resolution failed',
  [ERROR_CODES.SSL_ERROR]: 'SSL/TLS error',
  [ERROR_CODES.PROXY_ERROR]: 'Proxy error',
  
  [ERROR_CODES.DATABASE_ERROR]: 'Database error occurred',
  [ERROR_CODES.CONNECTION_FAILED]: 'Database connection failed',
  [ERROR_CODES.QUERY_FAILED]: 'Database query failed',
  [ERROR_CODES.TRANSACTION_FAILED]: 'Database transaction failed',
  [ERROR_CODES.CONSTRAINT_VIOLATION]: 'Database constraint violation',
  [ERROR_CODES.DUPLICATE_ENTRY]: 'Duplicate entry exists',
  [ERROR_CODES.RECORD_NOT_FOUND]: 'Record not found',
  [ERROR_CODES.OPTIMISTIC_LOCK_EXCEPTION]: 'Optimistic lock exception',
  
  [ERROR_CODES.PROCESSING_FAILED]: 'Processing failed',
  [ERROR_CODES.PARSING_FAILED]: 'Failed to parse document',
  [ERROR_CODES.GENERATION_FAILED]: 'CV generation failed',
  [ERROR_CODES.ANALYSIS_FAILED]: 'CV analysis failed',
  [ERROR_CODES.OPTIMIZATION_FAILED]: 'Optimization failed',
  [ERROR_CODES.CONVERSION_FAILED]: 'File conversion failed',
  [ERROR_CODES.PROCESSING_TIMEOUT]: 'Processing timeout',
  [ERROR_CODES.PROCESSING_CANCELLED]: 'Processing cancelled',
  [ERROR_CODES.INSUFFICIENT_RESOURCES]: 'Insufficient resources',
  [ERROR_CODES.QUEUE_FULL]: 'Processing queue is full',
  
  [ERROR_CODES.EXTERNAL_SERVICE_ERROR]: 'External service error',
  [ERROR_CODES.API_RATE_LIMIT]: 'API rate limit exceeded',
  [ERROR_CODES.API_QUOTA_EXCEEDED]: 'API quota exceeded',
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 'Service temporarily unavailable',
  [ERROR_CODES.SERVICE_TIMEOUT]: 'Service timeout',
  [ERROR_CODES.INVALID_API_RESPONSE]: 'Invalid API response',
  [ERROR_CODES.AI_SERVICE_ERROR]: 'AI service error',
  [ERROR_CODES.STORAGE_SERVICE_ERROR]: 'Storage service error',
  [ERROR_CODES.EMAIL_SERVICE_ERROR]: 'Email service error',
  
  [ERROR_CODES.INTERNAL_ERROR]: 'Internal server error',
  [ERROR_CODES.CONFIG_ERROR]: 'Configuration error',
  [ERROR_CODES.SYSTEM_OVERLOAD]: 'System overload',
  [ERROR_CODES.MAINTENANCE_MODE]: 'System in maintenance mode',
  [ERROR_CODES.FEATURE_DISABLED]: 'Feature is disabled',
  [ERROR_CODES.VERSION_MISMATCH]: 'Version mismatch',
  [ERROR_CODES.DEPENDENCY_ERROR]: 'Dependency error',
  
  [ERROR_CODES.INVALID_INPUT]: 'Invalid input provided',
  [ERROR_CODES.MALFORMED_REQUEST]: 'Malformed request',
  [ERROR_CODES.MISSING_PARAMETERS]: 'Missing required parameters',
  [ERROR_CODES.INVALID_PARAMETERS]: 'Invalid parameters',
  [ERROR_CODES.UNSUPPORTED_OPERATION]: 'Unsupported operation',
  
  [ERROR_CODES.BUSINESS_RULE_VIOLATION]: 'Business rule violation',
  [ERROR_CODES.WORKFLOW_ERROR]: 'Workflow error',
  [ERROR_CODES.STATE_TRANSITION_ERROR]: 'Invalid state transition',
  [ERROR_CODES.PRECONDITION_FAILED]: 'Precondition failed',
  [ERROR_CODES.POSTCONDITION_FAILED]: 'Postcondition failed',
  [ERROR_CODES.INVARIANT_VIOLATION]: 'Invariant violation'
} as const;

// ============================================================================
// ERROR CATEGORY MAPPINGS
// ============================================================================

export const ERROR_CATEGORY_MAPPINGS: Record<string, ErrorCategory> = {
  [ERROR_CODES.VALIDATION_FAILED]: ERROR_CATEGORIES.VALIDATION,
  [ERROR_CODES.REQUIRED_FIELD_MISSING]: ERROR_CATEGORIES.VALIDATION,
  [ERROR_CODES.INVALID_FORMAT]: ERROR_CATEGORIES.VALIDATION,
  [ERROR_CODES.VALUE_OUT_OF_RANGE]: ERROR_CATEGORIES.VALIDATION,
  [ERROR_CODES.INVALID_EMAIL]: ERROR_CATEGORIES.VALIDATION,
  [ERROR_CODES.INVALID_PHONE]: ERROR_CATEGORIES.VALIDATION,
  [ERROR_CODES.INVALID_URL]: ERROR_CATEGORIES.VALIDATION,
  [ERROR_CODES.INVALID_DATE]: ERROR_CATEGORIES.VALIDATION,
  [ERROR_CODES.INVALID_PASSWORD]: ERROR_CATEGORIES.VALIDATION,
  [ERROR_CODES.PASSWORD_TOO_WEAK]: ERROR_CATEGORIES.VALIDATION,
  [ERROR_CODES.INVALID_FILE_TYPE]: ERROR_CATEGORIES.VALIDATION,
  [ERROR_CODES.FILE_TOO_LARGE]: ERROR_CATEGORIES.VALIDATION,
  
  [ERROR_CODES.INVALID_CREDENTIALS]: ERROR_CATEGORIES.AUTHENTICATION,
  [ERROR_CODES.TOKEN_EXPIRED]: ERROR_CATEGORIES.AUTHENTICATION,
  [ERROR_CODES.TOKEN_INVALID]: ERROR_CATEGORIES.AUTHENTICATION,
  [ERROR_CODES.TOKEN_MISSING]: ERROR_CATEGORIES.AUTHENTICATION,
  [ERROR_CODES.LOGIN_FAILED]: ERROR_CATEGORIES.AUTHENTICATION,
  [ERROR_CODES.REGISTRATION_FAILED]: ERROR_CATEGORIES.AUTHENTICATION,
  [ERROR_CODES.EMAIL_NOT_VERIFIED]: ERROR_CATEGORIES.AUTHENTICATION,
  [ERROR_CODES.ACCOUNT_LOCKED]: ERROR_CATEGORIES.AUTHENTICATION,
  [ERROR_CODES.TOO_MANY_LOGIN_ATTEMPTS]: ERROR_CATEGORIES.AUTHENTICATION,
  
  [ERROR_CODES.UNAUTHORIZED]: ERROR_CATEGORIES.AUTHORIZATION,
  [ERROR_CODES.FORBIDDEN]: ERROR_CATEGORIES.AUTHORIZATION,
  [ERROR_CODES.INSUFFICIENT_PERMISSIONS]: ERROR_CATEGORIES.AUTHORIZATION,
  [ERROR_CODES.RESOURCE_ACCESS_DENIED]: ERROR_CATEGORIES.AUTHORIZATION,
  [ERROR_CODES.FEATURE_NOT_AVAILABLE]: ERROR_CATEGORIES.AUTHORIZATION,
  [ERROR_CODES.SUBSCRIPTION_REQUIRED]: ERROR_CATEGORIES.AUTHORIZATION,
  
  [ERROR_CODES.NETWORK_ERROR]: ERROR_CATEGORIES.NETWORK,
  [ERROR_CODES.REQUEST_TIMEOUT]: ERROR_CATEGORIES.NETWORK,
  [ERROR_CODES.CONNECTION_REFUSED]: ERROR_CATEGORIES.NETWORK,
  [ERROR_CODES.DNS_ERROR]: ERROR_CATEGORIES.NETWORK,
  [ERROR_CODES.SSL_ERROR]: ERROR_CATEGORIES.NETWORK,
  [ERROR_CODES.PROXY_ERROR]: ERROR_CATEGORIES.NETWORK,
  
  [ERROR_CODES.DATABASE_ERROR]: ERROR_CATEGORIES.DATABASE,
  [ERROR_CODES.CONNECTION_FAILED]: ERROR_CATEGORIES.DATABASE,
  [ERROR_CODES.QUERY_FAILED]: ERROR_CATEGORIES.DATABASE,
  [ERROR_CODES.TRANSACTION_FAILED]: ERROR_CATEGORIES.DATABASE,
  [ERROR_CODES.CONSTRAINT_VIOLATION]: ERROR_CATEGORIES.DATABASE,
  [ERROR_CODES.DUPLICATE_ENTRY]: ERROR_CATEGORIES.DATABASE,
  [ERROR_CODES.RECORD_NOT_FOUND]: ERROR_CATEGORIES.DATABASE,
  [ERROR_CODES.OPTIMISTIC_LOCK_EXCEPTION]: ERROR_CATEGORIES.DATABASE,
  
  [ERROR_CODES.PROCESSING_FAILED]: ERROR_CATEGORIES.PROCESSING,
  [ERROR_CODES.PARSING_FAILED]: ERROR_CATEGORIES.PROCESSING,
  [ERROR_CODES.GENERATION_FAILED]: ERROR_CATEGORIES.PROCESSING,
  [ERROR_CODES.ANALYSIS_FAILED]: ERROR_CATEGORIES.PROCESSING,
  [ERROR_CODES.OPTIMIZATION_FAILED]: ERROR_CATEGORIES.PROCESSING,
  [ERROR_CODES.CONVERSION_FAILED]: ERROR_CATEGORIES.PROCESSING,
  [ERROR_CODES.PROCESSING_TIMEOUT]: ERROR_CATEGORIES.PROCESSING,
  [ERROR_CODES.PROCESSING_CANCELLED]: ERROR_CATEGORIES.PROCESSING,
  [ERROR_CODES.INSUFFICIENT_RESOURCES]: ERROR_CATEGORIES.PROCESSING,
  [ERROR_CODES.QUEUE_FULL]: ERROR_CATEGORIES.PROCESSING
};

// ============================================================================
// ERROR SEVERITY MAPPINGS
// ============================================================================

export const ERROR_SEVERITY_MAPPINGS: Record<string, ErrorSeverity> = {
  [ERROR_CODES.VALIDATION_FAILED]: ERROR_SEVERITY_LEVELS.LOW,
  [ERROR_CODES.REQUIRED_FIELD_MISSING]: ERROR_SEVERITY_LEVELS.LOW,
  [ERROR_CODES.INVALID_FORMAT]: ERROR_SEVERITY_LEVELS.LOW,
  [ERROR_CODES.VALUE_OUT_OF_RANGE]: ERROR_SEVERITY_LEVELS.LOW,
  [ERROR_CODES.INVALID_EMAIL]: ERROR_SEVERITY_LEVELS.LOW,
  [ERROR_CODES.INVALID_PHONE]: ERROR_SEVERITY_LEVELS.LOW,
  [ERROR_CODES.INVALID_URL]: ERROR_SEVERITY_LEVELS.LOW,
  [ERROR_CODES.INVALID_DATE]: ERROR_SEVERITY_LEVELS.LOW,
  [ERROR_CODES.INVALID_PASSWORD]: ERROR_SEVERITY_LEVELS.LOW,
  [ERROR_CODES.PASSWORD_TOO_WEAK]: ERROR_SEVERITY_LEVELS.LOW,
  [ERROR_CODES.INVALID_FILE_TYPE]: ERROR_SEVERITY_LEVELS.MEDIUM,
  [ERROR_CODES.FILE_TOO_LARGE]: ERROR_SEVERITY_LEVELS.MEDIUM,
  
  [ERROR_CODES.INVALID_CREDENTIALS]: ERROR_SEVERITY_LEVELS.MEDIUM,
  [ERROR_CODES.TOKEN_EXPIRED]: ERROR_SEVERITY_LEVELS.MEDIUM,
  [ERROR_CODES.TOKEN_INVALID]: ERROR_SEVERITY_LEVELS.HIGH,
  [ERROR_CODES.TOKEN_MISSING]: ERROR_SEVERITY_LEVELS.MEDIUM,
  [ERROR_CODES.LOGIN_FAILED]: ERROR_SEVERITY_LEVELS.MEDIUM,
  [ERROR_CODES.REGISTRATION_FAILED]: ERROR_SEVERITY_LEVELS.MEDIUM,
  [ERROR_CODES.EMAIL_NOT_VERIFIED]: ERROR_SEVERITY_LEVELS.LOW,
  [ERROR_CODES.ACCOUNT_LOCKED]: ERROR_SEVERITY_LEVELS.HIGH,
  [ERROR_CODES.TOO_MANY_LOGIN_ATTEMPTS]: ERROR_SEVERITY_LEVELS.HIGH,
  
  [ERROR_CODES.UNAUTHORIZED]: ERROR_SEVERITY_LEVELS.MEDIUM,
  [ERROR_CODES.FORBIDDEN]: ERROR_SEVERITY_LEVELS.MEDIUM,
  [ERROR_CODES.INSUFFICIENT_PERMISSIONS]: ERROR_SEVERITY_LEVELS.MEDIUM,
  [ERROR_CODES.RESOURCE_ACCESS_DENIED]: ERROR_SEVERITY_LEVELS.MEDIUM,
  [ERROR_CODES.FEATURE_NOT_AVAILABLE]: ERROR_SEVERITY_LEVELS.LOW,
  [ERROR_CODES.SUBSCRIPTION_REQUIRED]: ERROR_SEVERITY_LEVELS.LOW,
  
  [ERROR_CODES.NETWORK_ERROR]: ERROR_SEVERITY_LEVELS.HIGH,
  [ERROR_CODES.REQUEST_TIMEOUT]: ERROR_SEVERITY_LEVELS.MEDIUM,
  [ERROR_CODES.CONNECTION_REFUSED]: ERROR_SEVERITY_LEVELS.HIGH,
  [ERROR_CODES.DNS_ERROR]: ERROR_SEVERITY_LEVELS.HIGH,
  [ERROR_CODES.SSL_ERROR]: ERROR_SEVERITY_LEVELS.CRITICAL,
  [ERROR_CODES.PROXY_ERROR]: ERROR_SEVERITY_LEVELS.HIGH,
  
  [ERROR_CODES.DATABASE_ERROR]: ERROR_SEVERITY_LEVELS.CRITICAL,
  [ERROR_CODES.CONNECTION_FAILED]: ERROR_SEVERITY_LEVELS.CRITICAL,
  [ERROR_CODES.QUERY_FAILED]: ERROR_SEVERITY_LEVELS.HIGH,
  [ERROR_CODES.TRANSACTION_FAILED]: ERROR_SEVERITY_LEVELS.HIGH,
  [ERROR_CODES.CONSTRAINT_VIOLATION]: ERROR_SEVERITY_LEVELS.MEDIUM,
  [ERROR_CODES.DUPLICATE_ENTRY]: ERROR_SEVERITY_LEVELS.MEDIUM,
  [ERROR_CODES.RECORD_NOT_FOUND]: ERROR_SEVERITY_LEVELS.LOW,
  [ERROR_CODES.OPTIMISTIC_LOCK_EXCEPTION]: ERROR_SEVERITY_LEVELS.MEDIUM,
  
  [ERROR_CODES.PROCESSING_FAILED]: ERROR_SEVERITY_LEVELS.HIGH,
  [ERROR_CODES.PARSING_FAILED]: ERROR_SEVERITY_LEVELS.HIGH,
  [ERROR_CODES.GENERATION_FAILED]: ERROR_SEVERITY_LEVELS.HIGH,
  [ERROR_CODES.ANALYSIS_FAILED]: ERROR_SEVERITY_LEVELS.MEDIUM,
  [ERROR_CODES.OPTIMIZATION_FAILED]: ERROR_SEVERITY_LEVELS.LOW,
  [ERROR_CODES.CONVERSION_FAILED]: ERROR_SEVERITY_LEVELS.HIGH,
  [ERROR_CODES.PROCESSING_TIMEOUT]: ERROR_SEVERITY_LEVELS.MEDIUM,
  [ERROR_CODES.PROCESSING_CANCELLED]: ERROR_SEVERITY_LEVELS.LOW,
  [ERROR_CODES.INSUFFICIENT_RESOURCES]: ERROR_SEVERITY_LEVELS.HIGH,
  [ERROR_CODES.QUEUE_FULL]: ERROR_SEVERITY_LEVELS.MEDIUM,
  
  [ERROR_CODES.INTERNAL_ERROR]: ERROR_SEVERITY_LEVELS.CRITICAL,
  [ERROR_CODES.CONFIG_ERROR]: ERROR_SEVERITY_LEVELS.CRITICAL,
  [ERROR_CODES.SYSTEM_OVERLOAD]: ERROR_SEVERITY_LEVELS.HIGH,
  [ERROR_CODES.MAINTENANCE_MODE]: ERROR_SEVERITY_LEVELS.LOW,
  [ERROR_CODES.FEATURE_DISABLED]: ERROR_SEVERITY_LEVELS.LOW,
  [ERROR_CODES.VERSION_MISMATCH]: ERROR_SEVERITY_LEVELS.MEDIUM,
  [ERROR_CODES.DEPENDENCY_ERROR]: ERROR_SEVERITY_LEVELS.HIGH
};